models:
  - name: claude-4-5-sonnet
    provider: bedrock
    model_id: "arn:aws:bedrock:us-east-1:033792130535:inference-profile/us.anthropic.claude-sonnet-4-5-20250929-v1:0"
  - name: claude-4-5-haiku
    provider: bedrock
    model_id: "arn:aws:bedrock:us-east-1:033792130535:inference-profile/us.anthropic.claude-haiku-4-5-20251001-v1:0"
  - name: claude-3-5-sonnet
    provider: bedrock
    model_id: "anthropic.claude-3-5-sonnet-20240620-v1:0"
  - name: claude-3-5-haiku
    provider: bedrock
    model_id: "arn:aws:bedrock:us-east-1:033792130535:inference-profile/us.anthropic.claude-3-5-haiku-20241022-v1:0"